# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160812_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='unique_id',
            new_name='id',
        ),
    ]
