# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='id',
        ),
        migrations.AddField(
            model_name='donor',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
